// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FUCounter_App
{
	public partial class EditRecordsView : UIView
	{
		public EditRecordsView (IntPtr handle) : base (handle)
		{
		}
	}
}
