// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FUCounter_App
{
	public partial class EditViewController : UIViewController
	{
		public CaseCount MasterRecord = null;

		public EditViewController (IntPtr handle) : base (handle)
		{
		}

		partial void UndoLast (MonoTouch.Foundation.NSObject sender)
		{

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			// loads the ui with last record
			GraftRecord rec = (GraftRecord) MasterRecord._allRecords [MasterRecord._allRecords.Count - 1];
			if (rec == null)
				return;
			textboxHairCount.Text = rec.HairCount.ToString ();
			textboxRecordNum.Text = MasterRecord._allRecords.Count.ToString();
			textboxTerminalHairCount.Text = rec.TerminalHairCount.ToString ();
			textBoxTxDHairCount.Text = rec.TxdHairCount.ToString ();
			textboxTxdTerminalHairCount.Text = rec.TxdTerminalHairCount.ToString ();
			selectorGroupNumber.SelectedSegment = rec.GroupNumber -1;
			StepRecordControl.MinimumValue = 1;
			StepRecordControl.MaximumValue = MasterRecord._allRecords.Count;
			StepRecordControl.Value = StepRecordControl.MaximumValue;
		}

		public void SetMasterRecord(CaseCount masterRecord)
		{
			MasterRecord = masterRecord;
		}

		private void FindLastRecord()
		{


		}

		public void PutRecordOnUI(int index)
		{

		}

		partial void TextBoxOkay (MonoTouch.Foundation.NSObject sender)
		{


		}

		partial void StepRecordEvent (MonoTouch.Foundation.NSObject sender)
		{

			GraftRecord rec = (GraftRecord) MasterRecord._allRecords[(int)StepRecordControl.Value-1];
			if (rec == null)
				return;
			textboxHairCount.Text = rec.HairCount.ToString ();
			textboxRecordNum.Text = ((int)StepRecordControl.Value).ToString();
			textboxTerminalHairCount.Text = rec.TerminalHairCount.ToString ();
			textBoxTxDHairCount.Text = rec.TxdHairCount.ToString ();
			textboxTxdTerminalHairCount.Text = rec.TxdTerminalHairCount.ToString ();
			selectorGroupNumber.SelectedSegment = rec.GroupNumber -1;
		}
	}
}
