// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FUCounter_App
{
	public partial class EditViewController : UIViewController
	{
		public CaseCount MasterRecord = null;

		public EditViewController (IntPtr handle) : base (handle)
		{
		}

		partial void UndoLast (UIButton sender)  
		{

		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			// loads the ui with last record
			if (MasterRecord == null)
				return;
			GraftRecord rec = (GraftRecord) MasterRecord._allRecords [MasterRecord._allRecords.Count - 1];
			if (rec == null)
				return;
			textboxHairCount.Text = rec.HairCount.ToString ();
			textboxRecordNum.Text = MasterRecord._allRecords.Count.ToString();
			textboxTerminalHairCount.Text = rec.TerminalHairCount.ToString ();
			textBoxTxDHairCount.Text = rec.TxdHairCount.ToString ();
			textboxTxdTerminalHairCount.Text = rec.TxdTerminalHairCount.ToString ();
			selectorGroupNumber.SelectedSegment = rec.GroupNumber -1;
			StepRecordControl.MinimumValue = 1;
			StepRecordControl.MaximumValue = MasterRecord._allRecords.Count;
			StepRecordControl.Value = StepRecordControl.MaximumValue;
		}

		public void SetMasterRecord(ref CaseCount masterRecord)
		{
			MasterRecord = masterRecord;
		}

		private void FindLastRecord()
		{


		}

		public void PutRecordOnUI(int index)
		{

		}

		GraftRecord undoRec = null;
		partial void TextBoxOkay (UIButton sender)
		{
			undoRec = (GraftRecord) MasterRecord._allRecords[(int)StepRecordControl.Value-1];
			if (undoRec == null)
				return;

			((GraftRecord) MasterRecord._allRecords[(int)StepRecordControl.Value-1]).TerminalHairCount = Convert.ToInt16(textboxTerminalHairCount.Text);
			((GraftRecord) MasterRecord._allRecords[(int)StepRecordControl.Value-1]).TxdHairCount = Convert.ToInt16(textBoxTxDHairCount.Text);
			((GraftRecord) MasterRecord._allRecords[(int)StepRecordControl.Value-1]).TxdTerminalHairCount = Convert.ToInt16(textboxTxdTerminalHairCount.Text);
			((GraftRecord) MasterRecord._allRecords[(int)StepRecordControl.Value-1]).GroupNumber = Convert.ToInt16(selectorGroupNumber.SelectedSegment)-1;

		}

		partial void StepRecordEvent (UIStepper sender)
		{

			GraftRecord rec = (GraftRecord) MasterRecord._allRecords[(int)StepRecordControl.Value-1];
			if (rec == null)
				return;
			textboxHairCount.Text = rec.HairCount.ToString ();
			textboxRecordNum.Text = ((int)StepRecordControl.Value).ToString();
			textboxTerminalHairCount.Text = rec.TerminalHairCount.ToString ();
			textBoxTxDHairCount.Text = rec.TxdHairCount.ToString ();
			textboxTxdTerminalHairCount.Text = rec.TxdTerminalHairCount.ToString ();
			selectorGroupNumber.SelectedSegment = rec.GroupNumber -1;
		}

		public override void ViewDidDisappear(bool animated)
		{
			base.ViewDidDisappear (animated);
		}  


		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);
			try{
				((FUCounter_AppViewController)segue.DestinationViewController).SetMasterRecord(MasterRecord);
			}
			catch(Exception e) {

			}

		}
	}
}
