// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FUCounter_App
{
	public partial class EditViewController : UIViewController
	{
		public CaseCount MasterRecord = null;

		public EditViewController (IntPtr handle) : base (handle)
		{
		}

		partial void UndoLast (MonoTouch.Foundation.NSObject sender)
		{

		}

		public void SetMasterRecord(CaseCount masterRecord)
		{
			MasterRecord = masterRecord;
		}

		private void FindLastRecord()
		{


		}

		public void PutRecordOnUI(int index)
		{

		}

	}
}
