// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FUCounter_App
{
	public partial class InfoViewController : UIViewController
	{
		public InfoViewController (IntPtr handle) : base (handle)
		{
			UIWebcontroller.LoadRequest(new NSUrlRequest(new NSUrl("http://wwww.restorationrobotics.com")));
			UIWebcontroller.ScalesPageToFit = true;
		}
	}
}
