// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.iAd;

namespace FUCounter_App
{
	public partial class RRAdBannerView : ADBannerView
	{
		public RRAdBannerView (IntPtr handle) : base (handle)
		{
		}
	}
}
